create table if not exists `characteristic_names`
(
`language_id` tinyint unsigned not null,
`characteristic_id` tinyint unsigned not null,

`name` varchar(40) not null,

primary key (
	`language_id`,
	`characteristic_id`
),
foreign key (`language_id`) references `languages` (`id`)
	on delete restrict
	on update cascade,
foreign key (`characteristic_id`) references `characteristics` (`id`)
	on delete restrict
	on update cascade
) engine = InnoDB;


insert into `characteristic_names` (
	`language_id`,
	`characteristic_id`,
	`name`
) values
(1, 1, "たべるのが　だいすき。"),
(1, 2, "ひるねを　よくする。"),
(1, 3, "いねむりが　おおい。"),
(1, 4, "ものを　よく　ちらかす。"),
(1, 5, "のんびりするのが　すき。"),
(1, 6, "ちからが　じまん。"),
(1, 7, "あばれることが　すき。"),
(1, 8, "ちょっと　おこりっぽい。"),
(1, 9, "ケンカを　するのが　すき。"),
(1, 10, "ちのけが　おおい。"),
(1, 11, "からだが　じょうぶ。"),
(1, 12, "うたれ　づよい。"),
(1, 13, "ねばり　づよい。"),
(1, 14, "しんぼう　づよい。"),
(1, 15, "がまん　づよい。"),
(1, 16, "かけっこが　すき。"),
(1, 17, "ものおとに　びんかん。"),
(1, 18, "おっちょこちょい。"),
(1, 19, "すこし　おちょうしもの。"),
(1, 20, "にげるのが　はやい。"),
(1, 21, "こうきしんが　つよい。"),
(1, 22, "イタズラが　すき。"),
(1, 23, "ぬけめが　ない。"),
(1, 24, "かんがえごとが　おおい。"),
(1, 25, "とても　きちょうめん。"),
(1, 26, "きが　つよい。"),
(1, 27, "ちょっぴり　みえっぱり。"),
(1, 28, "まけんきが　つよい。"),
(1, 29, "まけずぎらい。"),
(1, 30, "ちょっぴり　ごうじょう。"),
(2, 1, "Loves to eat"),
(2, 2, "Takes plenty of siestas"),
(2, 3, "Nods off a lot"),
(2, 4, "Scatters things often"),
(2, 5, "Likes to relax"),
(2, 6, "Proud of its power"),
(2, 7, "Likes to thrash about"),
(2, 8, "A little quick tempered"),
(2, 9, "Likes to fight"),
(2, 10, "Quick tempered"),
(2, 11, "Sturdy body"),
(2, 12, "Capable of taking hits"),
(2, 13, "Highly persistent"),
(2, 14, "Good endurance"),
(2, 15, "Good perseverance"),
(2, 16, "Likes to run"),
(2, 17, "Alert to sounds"),
(2, 18, "Impetuous and silly"),
(2, 19, "Somewhat of a clown"),
(2, 20, "Quick to flee"),
(2, 21, "Highly curious"),
(2, 22, "Mischievous"),
(2, 23, "Thoroughly cunning"),
(2, 24, "Often lost in thought"),
(2, 25, "Very finicky"),
(2, 26, "Strong willed"),
(2, 27, "Somewhat vain"),
(2, 28, "Strongly defiant"),
(2, 29, "Hates to lose"),
(2, 30, "Somewhat stubborn"),
(3, 1, "Adore manger."),
(3, 2, "S’assoupit souvent."),
(3, 3, "Dort beaucoup."),
(3, 4, "Éparpille des choses."),
(3, 5, "Aime se détendre."),
(3, 6, "Est fier de sa puissance."),
(3, 7, "Aime se démener."),
(3, 8, "Un peu coléreux."),
(3, 9, "Aime combattre."),
(3, 10, "S’emporte facilement."),
(3, 11, "Corps robuste."),
(3, 12, "Sait encaisser les coups."),
(3, 13, "Très obstiné."),
(3, 14, "Bonne endurance."),
(3, 15, "Persévérant."),
(3, 16, "Aime courir."),
(3, 17, "Attentif aux sons."),
(3, 18, "Bête et impulsif."),
(3, 19, "Aime faire le pitre."),
(3, 20, "Fuit rapidement."),
(3, 21, "Extrêmement curieux."),
(3, 22, "Coquin."),
(3, 23, "Très astucieux."),
(3, 24, "Souvent dans la lune."),
(3, 25, "Très particulier."),
(3, 26, "Très volontaire."),
(3, 27, "Un peu vaniteux."),
(3, 28, "Esprit rebelle."),
(3, 29, "A horreur de perdre."),
(3, 30, "Assez entêté."),
(4, 1, "Liebt es zu essen."),
(4, 2, "Nickt oft ein."),
(4, 3, "Schläft gern."),
(4, 4, "Macht oft Unordnung."),
(4, 5, "Mag es, sich zu entspannen."),
(4, 6, "Ist stolz auf seine Stärke."),
(4, 7, "Prügelt sich gern."),
(4, 8, "Besitzt Temperament."),
(4, 9, "Liebt Kämpfe."),
(4, 10, "Ist impulsiv."),
(4, 11, "Hat einen robusten Körper."),
(4, 12, "Kann Treffer gut verkraften."),
(4, 13, "Ist äußerst ausdauernd."),
(4, 14, "Hat eine gute Ausdauer."),
(4, 15, "Ist beharrlich."),
(4, 16, "Liebt es zu rennen."),
(4, 17, "Achtet auf Geräusche."),
(4, 18, "Ist ungestüm und einfältig."),
(4, 19, "Ist ein bisschen albern."),
(4, 20, "Flüchtet schnell."),
(4, 21, "Ist sehr neugierig."),
(4, 22, "Ist hinterhältig."),
(4, 23, "Ist äußerst gerissen."),
(4, 24, "Ist oft in Gedanken."),
(4, 25, "Ist sehr pedantisch."),
(4, 26, "Besitzt einen starken Willen."),
(4, 27, "Ist etwas eitel."),
(4, 28, "Ist sehr aufsässig."),
(4, 29, "Hasst Niederlagen."),
(4, 30, "Ist dickköpfig."),
(5, 1, "Adora mangiare."),
(5, 2, "Si addormenta spesso."),
(5, 3, "Dorme a lungo."),
(5, 4, "Lascia cose in giro."),
(5, 5, "Adora rilassarsi."),
(5, 6, "La forza è il suo vanto."),
(5, 7, "Adora dimenarsi."),
(5, 8, "Si arrabbia facilmente."),
(5, 9, "Adora lottare."),
(5, 10, "È facilmente irritabile."),
(5, 11, "Ha un corpo robusto."),
(5, 12, "Incassa bene i colpi."),
(5, 13, "È molto ostinato."),
(5, 14, "È molto paziente."),
(5, 15, "È molto tenace."),
(5, 16, "Adora correre."),
(5, 17, "Fa attenzione ai suoni."),
(5, 18, "È irruente e semplice."),
(5, 19, "È una specie di buffone."),
(5, 20, "Sa fuggire velocemente."),
(5, 21, "È un grande ficcanaso."),
(5, 22, "È alquanto vivace."),
(5, 23, "È estremamente sagace."),
(5, 24, "Si perde nel suo mondo."),
(5, 25, "È molto esigente."),
(5, 26, "Sa il fatto suo."),
(5, 27, "È abbastanza superficiale."),
(5, 28, "È molto insolente."),
(5, 29, "Non sopporta perdere."),
(5, 30, "È un po’ testardo."),
(6, 1, "Le encanta comer."),
(6, 2, "A menudo se duerme."),
(6, 3, "Duerme mucho."),
(6, 4, "Suele desordenar cosas."),
(6, 5, "Le gusta relajarse."),
(6, 6, "Está orgulloso de su fuerza."),
(6, 7, "Le gusta revolverse."),
(6, 8, "A veces se enfada."),
(6, 9, "Le gusta luchar."),
(6, 10, "Tiene mal genio."),
(6, 11, "Se caracteriza por su cuerpo resistente."),
(6, 12, "Es un buen fajador."),
(6, 13, "Es muy persistente."),
(6, 14, "Se caracteriza por ser muy resistente."),
(6, 15, "Es muy perseverante."),
(6, 16, "Le gusta correr."),
(6, 17, "Siempre tiene el oído alerta."),
(6, 18, "Resulta algo impetuoso y bobo."),
(6, 19, "Es un poco payaso."),
(6, 20, "Huye rápido."),
(6, 21, "Es extremadamente curioso."),
(6, 22, "Le gusta hacer travesuras."),
(6, 23, "Es muy astuto."),
(6, 24, "A menudo está en Babia."),
(6, 25, "Es muy melindroso."),
(6, 26, "Se distingue por ser muy voluntarioso."),
(6, 27, "Es algo orgulloso."),
(6, 28, "Es muy insolente."),
(6, 29, "Odia perder."),
(6, 30, "Es un poco cabezota."),
(7, 1, "먹는 것을 제일 좋아함."),
(7, 2, "낮잠을 잘 잠."),
(7, 3, "말뚝잠이 많음."),
(7, 4, "물건을 잘 어지름."),
(7, 5, "유유자적함을 좋아함."),
(7, 6, "힘자랑이 특기임."),
(7, 7, "난동부리기를 좋아함."),
(7, 8, "약간 화를 잘 내는 성미임."),
(7, 9, "싸움을 좋아함."),
(7, 10, "혈기가 왕성함."),
(7, 11, "몸이 튼튼함."),
(7, 12, "맷집이 강함."),
(7, 13, "끈질김."),
(7, 14, "인내심이 강함."),
(7, 15, "잘 참음."),
(7, 16, "달리기를 좋아함."),
(7, 17, "주위 소리에 민감함."),
(7, 18, "촐랑대는 성격임."),
(7, 19, "약간 우쭐쟁이임."),
(7, 20, "도망에는 선수임."),
(7, 21, "호기심이 강함."),
(7, 22, "장난을 좋아함."),
(7, 23, "빈틈이 없음."),
(7, 24, "걱정거리가 많음."),
(7, 25, "매우 꼼꼼함."),
(7, 26, "기가 센 성격임."),
(7, 27, "조금 겉치레를 좋아함."),
(7, 28, "오기가 센 성격임."),
(7, 29, "지기 싫어함."),
(7, 30, "조금 고집통이임."),
(8, 1, "たべるのが　だいすき。"),
(8, 2, "ひるねを　よくする。"),
(8, 3, "いねむりが　おおい。"),
(8, 4, "ものを　よく　ちらかす。"),
(8, 5, "のんびりするのが　すき。"),
(8, 6, "ちからが　じまん。"),
(8, 7, "あばれることが　すき。"),
(8, 8, "ちょっと　おこりっぽい。"),
(8, 9, "ケンカを　するのが　すき。"),
(8, 10, "ちのけが　おおい。"),
(8, 11, "からだが　じょうぶ。"),
(8, 12, "うたれ　づよい。"),
(8, 13, "ねばり　づよい。"),
(8, 14, "しんぼう　づよい。"),
(8, 15, "がまん　づよい。"),
(8, 16, "かけっこが　すき。"),
(8, 17, "ものおとに　びんかん。"),
(8, 18, "おっちょこちょい。"),
(8, 19, "すこし　おちょうしもの。"),
(8, 20, "にげるのが　はやい。"),
(8, 21, "こうきしんが　つよい。"),
(8, 22, "イタズラが　すき。"),
(8, 23, "ぬけめが　ない。"),
(8, 24, "かんがえごとが　おおい。"),
(8, 25, "とても　きちょうめん。"),
(8, 26, "きが　つよい。"),
(8, 27, "ちょっぴり　みえっぱり。"),
(8, 28, "まけんきが　つよい。"),
(8, 29, "まけずぎらい。"),
(8, 30, "ちょっぴり　ごうじょう。"),
(9, 1, "非常喜欢吃东西。"),
(9, 2, "经常睡午觉。"),
(9, 3, "常常打瞌睡。"),
(9, 4, "经常乱扔东西。"),
(9, 5, "喜欢悠然自在。"),
(9, 6, "以力气大为傲。"),
(9, 7, "喜欢胡闹。"),
(9, 8, "有点容易生气。"),
(9, 9, "喜欢打架。"),
(9, 10, "血气方刚。"),
(9, 11, "身体强壮。"),
(9, 12, "抗打能力强。"),
(9, 13, "顽强不屈。"),
(9, 14, "能吃苦耐劳。"),
(9, 15, "善于忍耐。"),
(9, 16, "喜欢比谁跑得快。"),
(9, 17, "对声音敏感。"),
(9, 18, "冒冒失失。"),
(9, 19, "有点容易得意忘形。"),
(9, 20, "逃得快。"),
(9, 21, "好奇心强。"),
(9, 22, "喜欢恶作剧。"),
(9, 23, "做事万无一失。"),
(9, 24, "经常思考。"),
(9, 25, "一丝不苟。"),
(9, 26, "性格强势。"),
(9, 27, "有一点点爱慕虚荣。"),
(9, 28, "争强好胜。"),
(9, 29, "不服输。"),
(9, 30, "有一点点固执。"),
(10, 1, "非常喜歡吃東西。"),
(10, 2, "經常睡午覺。"),
(10, 3, "常常打瞌睡。"),
(10, 4, "經常亂扔東西。"),
(10, 5, "喜歡悠然自在。"),
(10, 6, "以力氣大為傲。"),
(10, 7, "喜歡胡鬧。"),
(10, 8, "有點容易生氣。"),
(10, 9, "喜歡打架。"),
(10, 10, "血氣方剛。"),
(10, 11, "身體強壯。"),
(10, 12, "抗打能力強。"),
(10, 13, "頑強不屈。"),
(10, 14, "能吃苦耐勞。"),
(10, 15, "善於忍耐。"),
(10, 16, "喜歡比誰跑得快。"),
(10, 17, "對聲音敏感。"),
(10, 18, "冒冒失失。"),
(10, 19, "有點容易得意忘形。"),
(10, 20, "逃得快。"),
(10, 21, "好奇心強。"),
(10, 22, "喜歡惡作劇。"),
(10, 23, "做事萬無一失。"),
(10, 24, "經常思考。"),
(10, 25, "一絲不苟。"),
(10, 26, "性格強勢。"),
(10, 27, "有一點點愛慕虛榮。"),
(10, 28, "爭強好勝。"),
(10, 29, "不服輸。"),
(10, 30, "有一點點固執。")
;
