create table if not exists `nature_names`
(
`language_id` tinyint unsigned not null,
`nature_id` tinyint unsigned not null,

`name` varchar(7) not null,
`description` varchar(89) not null,

primary key (
	`language_id`,
	`nature_id`
),
foreign key (`language_id`) references `languages` (`id`)
	on delete restrict
	on update cascade,
foreign key (`nature_id`) references `natures` (`id`)
	on delete restrict
	on update cascade
) engine = InnoDB;


insert into `nature_names` (
	`language_id`,
	`nature_id`,
	`name`,
	`description`
) values
(1, 1, "がんばりや", "バランスよく　せいちょう　しやすい。"),
(1, 2, "さみしがり", "こうげきが　せいちょう　しやすい。ぼうぎょが　せいちょう　しにくい。"),
(1, 3, "ゆうかん", "こうげきが　せいちょう　しやすい。すばやさが　せいちょう　しにくい。"),
(1, 4, "いじっぱり", "こうげきが　せいちょう　しやすい。とくこうが　せいちょう　しにくい。"),
(1, 5, "やんちゃ", "こうげきが　せいちょう　しやすい。とくぼうが　せいちょう　しにくい。"),
(1, 6, "ずぶとい", "ぼうぎょが　せいちょう　しやすい。こうげきが　せいちょう　しにくい。"),
(1, 7, "すなお", "バランスよく　せいちょう　しやすい。"),
(1, 8, "のんき", "ぼうぎょが　せいちょう　しやすい。すばやさが　せいちょう　しにくい。"),
(1, 9, "わんぱく", "ぼうぎょが　せいちょう　しやすい。とくこうが　せいちょう　しにくい。"),
(1, 10, "のうてんき", "ぼうぎょが　せいちょう　しやすい。とくぼうが　せいちょう　しにくい。"),
(1, 11, "おくびょう", "すばやさが　せいちょう　しやすい。こうげきが　せいちょう　しにくい。"),
(1, 12, "せっかち", "すばやさが　せいちょう　しやすい。ぼうぎょが　せいちょう　しにくい。"),
(1, 13, "まじめ", "バランスよく　せいちょう　しやすい。"),
(1, 14, "ようき", "すばやさが　せいちょう　しやすい。とくこうが　せいちょう　しにくい。"),
(1, 15, "むじゃき", "すばやさが　せいちょう　しやすい。とくぼうが　せいちょう　しにくい。"),
(1, 16, "ひかえめ", "とくこうが　せいちょう　しやすい。こうげきが　せいちょう　しにくい。"),
(1, 17, "おっとり", "とくこうが　せいちょう　しやすい。ぼうぎょが　せいちょう　しにくい。"),
(1, 18, "れいせい", "とくこうが　せいちょう　しやすい。すばやさが　せいちょう　しにくい。"),
(1, 19, "てれや", "バランスよく　せいちょう　しやすい。"),
(1, 20, "うっかりや", "とくこうが　せいちょう　しやすい。とくぼうが　せいちょう　しにくい。"),
(1, 21, "おだやか", "とくぼうが　せいちょう　しやすい。こうげきが　せいちょう　しにくい。"),
(1, 22, "おとなしい", "とくぼうが　せいちょう　しやすい。ぼうぎょが　せいちょう　しにくい。"),
(1, 23, "なまいき", "とくぼうが　せいちょう　しやすい。すばやさが　せいちょう　しにくい。"),
(1, 24, "しんちょう", "とくぼうが　せいちょう　しやすい。とくこうが　せいちょう　しにくい。"),
(1, 25, "きまぐれ", "バランスよく　せいちょう　しやすい。"),
(2, 1, "Hardy", "Every stat grows in a balanced way."),
(2, 2, "Lonely", "Attack grows faster. Defense grows slower."),
(2, 3, "Brave", "Attack grows faster. Speed grows slower."),
(2, 4, "Adamant", "Attack grows faster. Sp. Atk grows slower."),
(2, 5, "Naughty", "Attack grows faster. Sp. Def grows slower."),
(2, 6, "Bold", "Defense grows faster. Attack grows slower."),
(2, 7, "Docile", "Every stat grows in a balanced way."),
(2, 8, "Relaxed", "Defense grows faster. Speed grows slower."),
(2, 9, "Impish", "Defense grows faster. Sp. Atk grows slower."),
(2, 10, "Lax", "Defense grows faster. Sp. Def grows slower."),
(2, 11, "Timid", "Speed grows faster. Attack grows slower."),
(2, 12, "Hasty", "Speed grows faster. Defense grows slower."),
(2, 13, "Serious", "Every stat grows in a balanced way."),
(2, 14, "Jolly", "Speed grows faster. Sp. Atk grows slower."),
(2, 15, "Naive", "Speed grows faster. Sp. Def grows slower."),
(2, 16, "Modest", "Sp. Atk grows faster. Attack grows slower."),
(2, 17, "Mild", "Sp. Atk grows faster. Defense grows slower."),
(2, 18, "Quiet", "Sp. Atk grows faster. Speed grows slower."),
(2, 19, "Bashful", "Every stat grows in a balanced way."),
(2, 20, "Rash", "Sp. Atk grows faster. Sp. Def grows slower."),
(2, 21, "Calm", "Sp. Def grows faster. Attack grows slower."),
(2, 22, "Gentle", "Sp. Def grows faster. Defense grows slower."),
(2, 23, "Sassy", "Sp. Def grows faster. Speed grows slower."),
(2, 24, "Careful", "Sp. Def grows faster. Sp. Atk grows slower."),
(2, 25, "Quirky", "Every stat grows in a balanced way."),
(3, 1, "Hardi", "Progresse de façon équilibrée."),
(3, 2, "Solo", "Progresse rapidement en Attaque, lentement en Défense."),
(3, 3, "Brave", "Progresse rapidement en Attaque, lentement en Vitesse."),
(3, 4, "Rigide", "Progresse rapidement en Attaque, lentement en Attaque Spéciale."),
(3, 5, "Mauvais", "Progresse rapidement en Attaque, lentement en Défense Spéciale."),
(3, 6, "Assuré", "Progresse rapidement en Défense, lentement en Attaque."),
(3, 7, "Docile", "Progresse de façon équilibrée."),
(3, 8, "Relax", "Progresse rapidement en Défense, lentement en Vitesse."),
(3, 9, "Malin", "Progresse rapidement en Défense, lentement en Attaque Spéciale."),
(3, 10, "Lâche", "Progresse rapidement en Défense, lentement en Défense Spéciale."),
(3, 11, "Timide", "Progresse rapidement en Vitesse, lentement en Attaque."),
(3, 12, "Pressé", "Progresse rapidement en Vitesse, lentement en Défense."),
(3, 13, "Sérieux", "Progresse de façon équilibrée."),
(3, 14, "Jovial", "Progresse rapidement en Vitesse, lentement en Attaque Spéciale."),
(3, 15, "Naïf", "Progresse rapidement en Vitesse, lentement en Défense Spéciale."),
(3, 16, "Modeste", "Progresse rapidement en Attaque Spéciale, lentement en Attaque."),
(3, 17, "Doux", "Progresse rapidement en Attaque Spéciale, lentement en Défense."),
(3, 18, "Discret", "Progresse rapidement en Attaque Spéciale, lentement en Vitesse."),
(3, 19, "Pudique", "Progresse de façon équilibrée."),
(3, 20, "Foufou", "Progresse rapidement en Attaque Spéciale, lentement en Défense Spéciale."),
(3, 21, "Calme", "Progresse rapidement en Défense Spéciale, lentement en Attaque."),
(3, 22, "Gentil", "Progresse rapidement en Défense Spéciale, lentement en Défense."),
(3, 23, "Malpoli", "Progresse rapidement en Défense Spéciale, lentement en Vitesse."),
(3, 24, "Prudent", "Progresse rapidement en Défense Spéciale, lentement en Attaque Spéciale."),
(3, 25, "Bizarre", "Progresse de façon équilibrée."),
(4, 1, "Robust", "Alle Statuswerte steigen in gleichem Maße."),
(4, 2, "Solo", "Erleichtert Training des Angriffs-Werts. Erschwert Training des Verteidigungs-Werts."),
(4, 3, "Mutig", "Erleichtert Training des Angriffs-Werts. Erschwert Training des Initiative-Werts."),
(4, 4, "Hart", "Erleichtert Training des Angriffs-Werts. Erschwert Training des Sp.-Ang.-Werts."),
(4, 5, "Frech", "Erleichtert Training des Angriffs-Werts. Erschwert Training des Sp.-Vert.-Werts."),
(4, 6, "Kühn", "Erleichtert Training des Vert.-Werts. Erschwert Training des Angriffs-Werts."),
(4, 7, "Sanft", "Alle Statuswerte steigen in gleichem Maße."),
(4, 8, "Locker", "Erleichtert Training des Vert.-Werts. Erschwert Training des Initiative-Werts."),
(4, 9, "Pfiffig", "Erleichtert Training des Vert.-Werts. Erschwert Training des Sp.-Ang.-Werts."),
(4, 10, "Lasch", "Erleichtert Training des Vert.-Werts. Erschwert Training des Sp.-Vert.-Werts."),
(4, 11, "Scheu", "Erleichtert Training des Initiative-Werts. Erschwert Training des Angriffs-Werts."),
(4, 12, "Hastig", "Erleichtert Training des Initiative-Werts. Erschwert Training des Vert.-Werts."),
(4, 13, "Ernst", "Alle Statuswerte steigen in gleichem Maße."),
(4, 14, "Froh", "Erleichtert Training des Initiative-Werts. Erschwert Training des Sp.-Ang.-Werts."),
(4, 15, "Naiv", "Erleichtert Training des Initiative-Werts. Erschwert Training des Sp.-Vert.-Werts."),
(4, 16, "Mäßig", "Erleichtert Training des Sp.-Ang.-Werts. Erschwert Training des Angriffs-Werts."),
(4, 17, "Mild", "Erleichtert Training des Sp.-Ang.-Werts. Erschwert Training des Vert.-Werts."),
(4, 18, "Ruhig", "Erleichtert Training des Sp.-Ang.-Werts. Erschwert Training des Initiative-Werts."),
(4, 19, "Zaghaft", "Alle Statuswerte steigen in gleichem Maße."),
(4, 20, "Hitzig", "Erleichtert Training des Sp.-Ang.-Werts. Erschwert Training des Sp.-Vert.-Werts."),
(4, 21, "Still", "Erleichtert Training des Sp.-Vert.-Werts. Erschwert Training des Angriffs-Werts."),
(4, 22, "Zart", "Erleichtert Training des Sp.-Vert.-Werts. Erschwert Training des Vert.-Werts."),
(4, 23, "Forsch", "Erleichtert Training des Sp.-Vert.-Werts. Erschwert Training des Initiative-Werts."),
(4, 24, "Sacht", "Erleichtert Training des Sp.-Vert.-Werts. Erschwert Training des Sp.-Ang.-Werts."),
(4, 25, "Kauzig", "Alle Statuswerte steigen in gleichem Maße."),
(5, 1, "Ardita", "Il Pokémon cresce in modo equilibrato."),
(5, 2, "Schiva", "L’Attacco tende a crescere di più. La Difesa tende a crescere di meno."),
(5, 3, "Audace", "L’Attacco tende a crescere di più. La Velocità tende a crescere di meno."),
(5, 4, "Decisa", "L’Attacco tende a crescere di più. L’Attacco Speciale tende a crescere di meno."),
(5, 5, "Birbona", "L’Attacco tende a crescere di più. La Difesa Speciale tende a crescere di meno."),
(5, 6, "Sicura", "La Difesa tende a crescere di più. L’Attacco tende a crescere di meno."),
(5, 7, "Docile", "Il Pokémon cresce in modo equilibrato."),
(5, 8, "Placida", "La Difesa tende a crescere di più. La Velocità tende a crescere di meno."),
(5, 9, "Scaltra", "La Difesa tende a crescere di più. L’Attacco Speciale tende a crescere di meno."),
(5, 10, "Fiacca", "La Difesa tende a crescere di più. La Difesa Speciale tende a crescere di meno."),
(5, 11, "Timida", "La Velocità tende a crescere di più. L’Attacco tende a crescere di meno."),
(5, 12, "Lesta", "La Velocità tende a crescere di più. La Difesa tende a crescere di meno."),
(5, 13, "Seria", "Il Pokémon cresce in modo equilibrato."),
(5, 14, "Allegra", "La Velocità tende a crescere di più. L’Attacco Speciale tende a crescere di meno."),
(5, 15, "Ingenua", "La Velocità tende a crescere di più. La Difesa Speciale tende a crescere di meno."),
(5, 16, "Modesta", "L’Attacco Speciale tende a crescere di più. L’Attacco tende a crescere di meno."),
(5, 17, "Mite", "L’Attacco Speciale tende a crescere di più. La Difesa tende a crescere di meno."),
(5, 18, "Quieta", "L’Attacco Speciale tende a crescere di più. La Velocità tende a crescere di meno."),
(5, 19, "Ritrosa", "Il Pokémon cresce in modo equilibrato."),
(5, 20, "Ardente", "L’Attacco Speciale tende a crescere di più. La Difesa Speciale tende a crescere di meno."),
(5, 21, "Calma", "La Difesa Speciale tende a crescere di più. L’Attacco tende a crescere di meno."),
(5, 22, "Gentile", "La Difesa Speciale tende a crescere di più. La Difesa tende a crescere di meno."),
(5, 23, "Vivace", "La Difesa Speciale tende a crescere di più. La Velocità tende a crescere di meno."),
(5, 24, "Cauta", "La Difesa Speciale tende a crescere di più. L’Attacco Speciale tende a crescere di meno."),
(5, 25, "Furba", "Il Pokémon cresce in modo equilibrato."),
(6, 1, "Fuerte", "Desarrollo equilibrado."),
(6, 2, "Huraña", "Facilidad para desarrollar Ataque. Dificultad para desarrollar Defensa."),
(6, 3, "Audaz", "Facilidad para desarrollar Ataque. Dificultad para desarrollar Velocidad."),
(6, 4, "Firme", "Facilidad para desarrollar Ataque. Dificultad para desarrollar Ataque Especial."),
(6, 5, "Pícara", "Facilidad para desarrollar Ataque. Dificultad para desarrollar Defensa Especial."),
(6, 6, "Osada", "Facilidad para desarrollar Defensa. Dificultad para desarrollar Ataque."),
(6, 7, "Dócil", "Desarrollo equilibrado."),
(6, 8, "Plácida", "Facilidad para desarrollar Defensa. Dificultad para desarrollar Velocidad."),
(6, 9, "Agitada", "Facilidad para desarrollar Defensa. Dificultad para desarrollar Ataque Especial."),
(6, 10, "Floja", "Facilidad para desarrollar Defensa. Dificultad para desarrollar Defensa Especial."),
(6, 11, "Miedosa", "Facilidad para desarrollar Velocidad. Dificultad para desarrollar Ataque."),
(6, 12, "Activa", "Facilidad para desarrollar Velocidad. Dificultad para desarrollar Defensa."),
(6, 13, "Seria", "Desarrollo equilibrado."),
(6, 14, "Alegre", "Facilidad para desarrollar Velocidad. Dificultad para desarrollar Ataque Especial."),
(6, 15, "Ingenua", "Facilidad para desarrollar Velocidad. Dificultad para desarrollar Defensa Especial."),
(6, 16, "Modesta", "Facilidad para desarrollar Ataque Especial. Dificultad para desarrollar Ataque."),
(6, 17, "Afable", "Facilidad para desarrollar Ataque Especial. Dificultad para desarrollar Defensa."),
(6, 18, "Mansa", "Facilidad para desarrollar Ataque Especial. Dificultad para desarrollar Velocidad."),
(6, 19, "Tímida", "Desarrollo equilibrado."),
(6, 20, "Alocada", "Facilidad para desarrollar Ataque Especial. Dificultad para desarrollar Defensa Especial."),
(6, 21, "Serena", "Facilidad para desarrollar Defensa Especial. Dificultad para desarrollar Ataque."),
(6, 22, "Amable", "Facilidad para desarrollar Defensa Especial. Dificultad para desarrollar Defensa."),
(6, 23, "Grosera", "Facilidad para desarrollar Defensa Especial. Dificultad para desarrollar Velocidad."),
(6, 24, "Cauta", "Facilidad para desarrollar Defensa Especial. Dificultad para desarrollar Ataque Especial."),
(6, 25, "Rara", "Desarrollo equilibrado."),
(7, 1, "노력", "밸런스 좋게 성장하기 쉽다."),
(7, 2, "외로움", "공격이 성장하기 쉽다. 방어가 성장하기 어렵다."),
(7, 3, "용감", "공격이 성장하기 쉽다. 스피드가 성장하기 어렵다."),
(7, 4, "고집", "공격이 성장하기 쉽다. 특수공격이 성장하기 어렵다."),
(7, 5, "개구쟁이", "공격이 성장하기 쉽다. 특수방어가 성장하기 어렵다."),
(7, 6, "대담", "방어가 성장하기 쉽다. 공격이 성장하기 어렵다."),
(7, 7, "온순", "밸런스 좋게 성장하기 쉽다."),
(7, 8, "무사태평", "방어가 성장하기 쉽다. 스피드가 성장하기 어렵다."),
(7, 9, "장난꾸러기", "방어가 성장하기 쉽다. 특수공격이 성장하기 어렵다."),
(7, 10, "촐랑", "방어가 성장하기 쉽다. 특수방어가 성장하기 어렵다."),
(7, 11, "겁쟁이", "스피드가 성장하기 쉽다. 공격이 성장하기 어렵다."),
(7, 12, "성급", "스피드가 성장하기 쉽다. 방어가 성장하기 어렵다."),
(7, 13, "성실", "밸런스 좋게 성장하기 쉽다."),
(7, 14, "명랑", "스피드가 성장하기 쉽다. 특수공격이 성장하기 어렵다."),
(7, 15, "천진난만", "스피드가 성장하기 쉽다. 특수방어가 성장하기 어렵다."),
(7, 16, "조심", "특수공격이 성장하기 쉽다. 공격이 성장하기 어렵다."),
(7, 17, "의젓", "특수공격이 성장하기 쉽다. 방어가 성장하기 어렵다."),
(7, 18, "냉정", "특수공격이 성장하기 쉽다. 스피드가 성장하기 어렵다."),
(7, 19, "수줍음", "밸런스 좋게 성장하기 쉽다."),
(7, 20, "덜렁", "특수공격이 성장하기 쉽다. 특수방어가 성장하기 어렵다."),
(7, 21, "차분", "특수방어가 성장하기 쉽다. 공격이 성장하기 어렵다."),
(7, 22, "얌전", "특수방어가 성장하기 쉽다. 방어가 성장하기 어렵다."),
(7, 23, "건방", "특수방어가 성장하기 쉽다. 스피드가 성장하기 어렵다."),
(7, 24, "신중", "특수방어가 성장하기 쉽다. 특수공격이 성장하기 어렵다."),
(7, 25, "변덕", "밸런스 좋게 성장하기 쉽다."),
(8, 1, "がんばりや", "バランスよく　成長しやすい。"),
(8, 2, "さみしがり", "攻撃が　成長しやすい。防御が　成長しにくい。"),
(8, 3, "ゆうかん", "攻撃が　成長しやすい。素早さが　成長しにくい。"),
(8, 4, "いじっぱり", "攻撃が　成長しやすい。特攻が　成長しにくい。"),
(8, 5, "やんちゃ", "攻撃が　成長しやすい。特防が　成長しにくい。"),
(8, 6, "ずぶとい", "防御が　成長しやすい。攻撃が　成長しにくい。"),
(8, 7, "すなお", "バランスよく　成長しやすい。"),
(8, 8, "のんき", "防御が　成長しやすい。素早さが　成長しにくい。"),
(8, 9, "わんぱく", "防御が　成長しやすい。特攻が　成長しにくい。"),
(8, 10, "のうてんき", "防御が　成長しやすい。特防が　成長しにくい。"),
(8, 11, "おくびょう", "素早さが　成長しやすい。攻撃が　成長しにくい。"),
(8, 12, "せっかち", "素早さが　成長しやすい。防御が　成長しにくい。"),
(8, 13, "まじめ", "バランスよく　成長しやすい。"),
(8, 14, "ようき", "素早さが　成長しやすい。特攻が　成長しにくい。"),
(8, 15, "むじゃき", "素早さが　成長しやすい。特防が　成長しにくい。"),
(8, 16, "ひかえめ", "特攻が　成長しやすい。攻撃が　成長しにくい。"),
(8, 17, "おっとり", "特攻が　成長しやすい。防御が　成長しにくい。"),
(8, 18, "れいせい", "特攻が　成長しやすい。素早さが　成長しにくい。"),
(8, 19, "てれや", "バランスよく　成長しやすい。"),
(8, 20, "うっかりや", "特攻が　成長しやすい。特防が　成長しにくい。"),
(8, 21, "おだやか", "特防が　成長しやすい。攻撃が　成長しにくい。"),
(8, 22, "おとなしい", "特防が　成長しやすい。防御が　成長しにくい。"),
(8, 23, "なまいき", "特防が　成長しやすい。素早さが　成長しにくい。"),
(8, 24, "しんちょう", "特防が　成長しやすい。特攻が　成長しにくい。"),
(8, 25, "きまぐれ", "バランスよく　成長しやすい。"),
(9, 1, "勤奋", "比较容易均衡地增长。"),
(9, 2, "怕寂寞", "攻击增长容易。防御增长困难。"),
(9, 3, "勇敢", "攻击增长容易。速度增长困难。"),
(9, 4, "固执", "攻击增长容易。特攻增长困难。"),
(9, 5, "顽皮", "攻击增长容易。特防增长困难。"),
(9, 6, "大胆", "防御增长容易。攻击增长困难。"),
(9, 7, "坦率", "比较容易均衡地增长。"),
(9, 8, "悠闲", "防御增长容易。速度增长困难。"),
(9, 9, "淘气", "防御增长容易。特攻增长困难。"),
(9, 10, "乐天", "防御增长容易。特防增长困难。"),
(9, 11, "胆小", "速度增长容易。攻击增长困难。"),
(9, 12, "急躁", "速度增长容易。防御增长困难。"),
(9, 13, "认真", "比较容易均衡地增长。"),
(9, 14, "爽朗", "速度增长容易。特攻增长困难。"),
(9, 15, "天真", "速度增长容易。特防增长困难。"),
(9, 16, "内敛", "特攻增长容易。攻击增长困难。"),
(9, 17, "慢吞吞", "特攻增长容易。防御增长困难。"),
(9, 18, "冷静", "特攻增长容易。速度增长困难。"),
(9, 19, "害羞", "比较容易均衡地增长。"),
(9, 20, "马虎", "特攻增长容易。特防增长困难。"),
(9, 21, "温和", "特防增长容易。攻击增长困难。"),
(9, 22, "温顺", "特防增长容易。防御增长困难。"),
(9, 23, "自大", "特防增长容易。速度增长困难。"),
(9, 24, "慎重", "特防增长容易。特攻增长困难。"),
(9, 25, "浮躁", "比较容易均衡地增长。"),
(10, 1, "勤奮", "能力容易均衡地成長。"),
(10, 2, "怕寂寞", "攻擊容易成長。防禦不易成長。"),
(10, 3, "勇敢", "攻擊容易成長。速度不易成長。"),
(10, 4, "固執", "攻擊容易成長。特攻不易成長。"),
(10, 5, "頑皮", "攻擊容易成長。特防不易成長。"),
(10, 6, "大膽", "防禦容易成長。攻擊不易成長。"),
(10, 7, "坦率", "能力容易均衡地成長。"),
(10, 8, "悠閒", "防禦容易成長。速度不易成長。"),
(10, 9, "淘氣", "防禦容易成長。特攻不易成長。"),
(10, 10, "樂天", "防禦容易成長。特防不易成長。"),
(10, 11, "膽小", "速度容易成長。攻擊不易成長。"),
(10, 12, "急躁", "速度容易成長。防禦不易成長。"),
(10, 13, "認真", "能力容易均衡地成長。"),
(10, 14, "爽朗", "速度容易成長。特攻不易成長。"),
(10, 15, "天真", "速度容易成長。特防不易成長。"),
(10, 16, "內斂", "特攻容易成長。攻擊不易成長。"),
(10, 17, "慢吞吞", "特攻容易成長。防禦不易成長。"),
(10, 18, "冷靜", "特攻容易成長。速度不易成長。"),
(10, 19, "害羞", "能力容易均衡地成長。"),
(10, 20, "馬虎", "特攻容易成長。特防不易成長。"),
(10, 21, "溫和", "特防容易成長。攻擊不易成長。"),
(10, 22, "溫順", "特防容易成長。防禦不易成長。"),
(10, 23, "自大", "特防容易成長。速度不易成長。"),
(10, 24, "慎重", "特防容易成長。特攻不易成長。"),
(10, 25, "浮躁", "能力容易均衡地成長。")
;
